# SPDX-License-Identifier: GPL-2.0
obj-y		+= typec.o
typec-y				:= class.o mux.o bus.o
obj-y	+= tcpm.o
obj-y				+= fusb302/
obj-$(CONFIG_TYPEC_TCPCI)	+= tcpci.o
obj-$(CONFIG_TYPEC_RT1711H)	+= tcpci_rt1711h.o
